### ISSUE TITLE
when trying to pick up baby it freezes mario

### ISSUE THREAD

**Issue by gabeio64** [Fluvian/tpp#106]
https://user-images.githubusercontent.com/121705654/233760857-fed573ae-543c-4ce0-ae64-5a6b2c1e4ee2.mp4

**Comment by WSDguy2014** [comment]
It's a _punch glitch_, this is intentional, you can read this [TPPCHANGELIST.txt](https://github.com/The1UPGuy/tpp/commit/1984d696b6daaccc6fa8466c27507991ed6fc6cd#diff-79fd24dd8c5fa9151eee8d95c0ac96c20593516e02be0a864e136cac1d58f417) file, which includes this:

> Punch glitch has been added. (to activate it, stop at a low speed and punch in a 5 frame window, if you do, Mario gets stuck in the punching pose)

You can stop freezing in a punching pose by simply jumping.

**Comment by The1UPGuy** [comment]
It is intentional yeah, here's footage of it happening in the actual demo: https://youtu.be/tFioIiu-yGw?t=8m19s
