### ISSUE TITLE
Blinking moustache with the press start icon

### ISSUE THREAD

**Issue by gdandsm64fan123** [Fluvian/tpp#116]
So i was playing in Mupen64FZ Plus (Android) and i noticed that Mario's moustache was blinking alongside the press start letters, it only files if i use the most accurrate plugin. Please fix this for other plugins!

**Comment by cursedUs64-git** [comment]
This is for every hack, and for vanilla sm64 too. Please go away 😊

**Comment by cursedUs64-git** [comment]
Please don't act like a dumb guy

**Comment by cursedUs64-git** [comment]
Just use gliden64

**Comment by gdandsm64fan123** [comment]
It doesnt happen in vanilla sm64 for me, and for any other hacks. Only TPP64.

**Comment by gdandsm64fan123** [comment]
And i also said it only fixed with the most accurate plugin. The other ones like Gliden64-fast and others have this bug and only happen in this rom. A normal sm64 rom doesnt have this problem.

**Comment by gdandsm64fan123** [comment]
Also curse you for literally just said to me to got away.

**Comment by Fluvian** [comment]
It's not our fault when the plugin you're using is bad. Just use the better plugin.

**Comment by gdandsm64fan123** [comment]
Nope, this wont end here, first of all, this is how you treat a user when they find a error that is common in rom hacks? Seriously? Just saying to go away? Thats an insult, i mean sure its a common bug but thats not the way to say to close the whole issue, first, in my experience i never presenced  any moustache-related / start menu graphically-related bugs on the emulator. Remember Project 95x? The romhack who stole TPP's assets? The moustache didnt blink, Not even on mobile. This is kinda absurd to be honest. But im thinking its a local build problem. Anyways, Out!

**Comment by riggles1** [comment]
> Nope, this wont end here, first of all, this is how you treat a user when they find a error that is common in rom hacks? Seriously? Just saying to go away? Thats an insult, i mean sure its a common bug but thats not the way to say to close the whole issue, first, in my experience i never presenced any moustache-related / start menu graphically-related bugs on the emulator. Remember Project 95x? The romhack who stole TPP's assets? The moustache didnt blink, Not even on mobile. This is kinda absurd to be honest. But im thinking its a local build problem. Anyways, Out!

The fault is on your end, you weren't taken seriously because it's fairly obvious even if the other user took it too far.

This hack works on N64 hardware with a flashcart, everything else will have inaccuracies depending on the emulation/plugin used, doesn't matter if vanilla has that effect intact with your specific platform or not. This works on hardware like intended, like a real n64 game would, that's the baseline. If you had more accurate emulation, the behavior would be correct like on an actual N64.

If you want to complain then the fault is the accuracy of the plugin you use (even then, don't complain, emulator devs focus on retail games first and foremost and are likely already aware what shortcuts that might interfere with hacks which won't affect retail games much)

Hacks that target emulators are bound to get outdated and not function well as emulators get more accurate, there's a ton of older SM64 hacks that only work with outdated emulator versions. But if the romhack target platform is real N64 hardware then there's no concern with emulation or fpga running it without flaws as those improve in accuracy over time.

**Comment by iProgramMC** [comment]
> Nope, this won't end here

Yes, it will. To reiterate, it's no one's fault that your experience on a (most likely) outdated emulator doesn't work properly - TPP targets real hardware and accurate emulators first and foremost.
